# Site wide configuration

title:            "JimKilleen.com"
locale:           en_US
url:              http://JimKilleen.com
baseurl:          ""

# Github Metadata integration
repository: JimKilleen/JimKilleen.github.io

# Additional Gems
gems:
  - jekyll-sitemap # Generates a sitemap.xml
  - jekyll-redirect-from # Allows you to redirect from other pages (will be useful in the future)

highlighter: rouge # For code syntax highlighting

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  input: GFM

# Includes and excludes -- some things you don't want to publish to the final site, like configs or readme files.
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
